/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { requireCurrentUser } from "@/lib/auth/current-user";
const fail = (status: number, error: string) => NextResponse.json({ error }, { status });
const db = () => createSupabaseAdminClient() as any;

export async function GET() { try { const user = await requireCurrentUser(); if (!user) return fail(401, "ログインが必要です"); const { data, error } = await db().from("matchmaking_queue").select("player_id,deck_id,status,queued_at,expires_at,battle_id").eq("player_id", user.id).maybeSingle(); if (error) throw error; return NextResponse.json({ entry: data }); } catch { return fail(500, "マッチング状態を取得できませんでした"); } }
export async function POST(request: Request) { try { const user = await requireCurrentUser(); if (!user) return fail(401, "ログインが必要です"); const body = await request.json().catch(() => ({})); const deckId = typeof body.deckId === "string" ? body.deckId : ""; if (!deckId) return fail(400, "デッキを選択してください"); const admin = db(); const { data: deck } = await admin.from("decks").select("id").eq("id", deckId).eq("owner_id", user.id).maybeSingle(); if (!deck) return fail(404, "データが見つかりません"); const { count } = await admin.from("deck_cards").select("id", { count: "exact", head: true }).eq("deck_id", deckId).eq("role", "action"); if (!count) return fail(400, "アクションカードが必要です"); const expiresAt = new Date(Date.now() + 120000).toISOString(); const { data, error } = await admin.from("matchmaking_queue").upsert({ player_id: user.id, deck_id: deckId, status: "queued", queued_at: new Date().toISOString(), expires_at: expiresAt, battle_id: null }).select().single(); if (error) throw error; return NextResponse.json({ entry: data }, { status: 201 }); } catch { return fail(500, "マッチングに参加できませんでした"); } }
export async function DELETE() { try { const user = await requireCurrentUser(); if (!user) return fail(401, "ログインが必要です"); const { error } = await db().from("matchmaking_queue").update({ status: "cancelled" }).eq("player_id", user.id).eq("status", "queued"); if (error) throw error; return NextResponse.json({ ok: true }); } catch { return fail(500, "マッチングをキャンセルできませんでした"); } }
